---
- name: Install COGNIT Frontend on dedicated host
  hosts: cognit
  tasks:
    - name: Add COGNIT apt repository file
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/cognit.list
        content: "deb [trusted=yes] {{ cognit_apt_repo }} stable main\n"
        mode: '0644'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update
      retries: 3
      delay: 5
      until: apt_update is success

    - name: Install opennebula-cognit-frontend
      ansible.builtin.apt:
        name: opennebula-cognit-frontend
        state: present
      register: package
      until: package is success
      retries: 3
      delay: 5

